using PRTelegramBot.Attributes;

namespace Community9Cold_Bot.Headers
{
    [InlineCommand]
    internal enum PRHeadlers
    {
        Example = 100,
        Example2,
        Example3,
        Example4,
        ExampleEntry,
        ExampleLurk,
        ExampleSniper,
        ExampleIGL,
        ExampleSupport,
        ExampleAddPlyaer,
        Roule = 200,
        RouleMM,
        RouleBK,
        RouleSplit,
        RouleRash,
        RouleFullZ,
        RouleEco,
        RouleFors,
        RouleSaves,
        RouleReg,
        Profil = 300,
        ProfilReg,
        Commands,
        ProfilRegSlash,

        TELEGRAMNAME,
        TELEGRAMID,
        STANDOFFNAME,
        STANDOFFID,
        TELEGRAMUSERNAME,

        ProfilPlz = 400,
        DellProfil,
        DellProfilYes,
        DellProfilAddS,
        DellProfilFinal,
        AddProfilEsport,
        AddProfilEsportYes,
        RedactProfil,
        RedactStandoffName,
        RedactStandoffID,
        RedactStandoffNameYes,
        RedactStandoffIDYes = 411,

        UpdateListBlack = 500,
        UpdateListWhite,
        UpdateListEsport,

        CaseMain = 600,
        CaseShop,
        Fable,

        Maps,
        AvaMember,
        AvaElder,
        AvaCoLeader,
        AvaLeader,
        AvaRed,
        AvaGreen,
        AvaBlack,
        AvaPink,
        AvaOrange,
        AvaBlue,
        AvaBirch,
        AvaPersonalize,
        AddNews,
        AddNewsYes,
        AddMember,
        AddElder,
        AddCoLeader,
        AddAvaO,
        AddAvaOYes,
        DellAvaO,
        DellAvaOYes,
        ProfilPlzPl,

        Play = 626,
        Play1P,
        Play2P,
        Play3P,
        Play4P,
        Play1Yes,
        Play2Yes,
        Play3Yes,
        Play4Yes,
        PlaySOne,
        PlaySTwo,
        PlaySThree,
        PlaySFour,

        DellPlayer = 640,
        DellPlayer1One,
        DellPlayer2One,
        DellPlayer3One,
        DellPlayer4One,
        DellPlayer5One,
        DellReplacement1One,
        DellReplacement2One,
        DellPlayer1Two,
        DellPlayer2Two,
        DellPlayer3Two,
        DellPlayer4Two,
        DellPlayer5Two,
        DellReplacement1Two,
        DellReplacement2Two,
        DellPlayer1Three,
        DellPlayer2Three,
        DellPlayer3Three,
        DellPlayer4Three,
        DellPlayer5Three,
        DellReplacement1Three,
        DellReplacement2Three,
        DellPlayer1Four,
        DellPlayer2Four,
        DellPlayer3Four,
        DellPlayer4Four,
        DellPlayer5Four,
        DellReplacement1Four,
        DellReplacement2Four

    }
}
